[[redirects]]
from = "/step-one/"
to ="/step-one/"
force = true
status = 200
conditions = {Role = ["sub"]}

[[redirects]]
from = "/product-entry"
to ="/product-entry/"
force = true
status = 200
conditions = {Role = ["sub"]}

[[redirects]]
from = "/"
to ="/dashboard/"
force = true
status = 200
conditions = {Role = ["sub"]}

[[redirects]]
from = "/"
to ="/home/"
force = true
status = 200
conditions = {Role = ["nosub"]}

[[redirects]]
from = "/step-one/"
to = "/"
force = true
status = 302

[[redirects]]
from = "/product-entry/"
to = "/"
force = true
status = 302

[[redirects]]
from = "/dashboard/"
to = "/"
force = true
status = 302

[[redirects]]
from = "/home/"
to = "/"
force = true
status = 302